collections:
  - name: "homepage"
    label: "Homepage Settings"
    files:
      - file: "content/homepage.md"
        label: "Main Page"
        name: "homepage"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "string" }
          - { label: "Hero Text", name: "hero_text", widget: "text" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "About Text", name: "about", widget: "markdown" }
          - { label: "Skills", name: "skills", widget: "list", field: { label: "Skill", name: "skill", widget: "string" } }
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Technologies", name: "technologies", widget: "string" }
              - { label: "Tags", name: "tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" } }
          - { label: "Blog Intro", name: "blog_intro", widget: "string" }
          - { label: "Blog CTA URL", name: "blog_cta_url", widget: "string" }
          - label: "Contact Info"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Location", name: "location", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - label: "Social Links"
                name: "socials"
                widget: "list"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
          - { label: "Footer Text", name: "footer", widget: "text" }
